### ISSUE TITLE
Using the middle click scroll on the main page reveals the page is too wide

### ISSUE THREAD

**Issue by tsimonq2** [ubuntu-mate/ubuntu-mate.org#11]
While it doesn't show up as its own scroll bar at the bottom of the screen, the banner on the main page is too wide, and this is only revealed when using the middle click scroll, revealing that you can go to the right more.

**Comment by lah7** [comment]
Our website has just been updated - the issue was largely down to the structure of the old banner, but with the new layout, this is no longer a bug. :bug: :tennis:
