### ISSUE TITLE
SHA256SUMS.gpg: bad signature

### ISSUE THREAD

**Issue by xanderdin** [ubuntu-mate/ubuntu-mate.org#117]
### Details about the problem

I'm not sure where to report the issue and initially reported it at https://ubuntu-mate.community/t/sha256sums-gpg-bad-signature/23884

When trying to verify GPG signature of SHA256SUMS file for ubuntu-mate-20.04.2.0-desktop-amd64.iso image the verification fails:
```
gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS
```
```
pg: Signature made Thu Feb 11 22:01:40 2021 MSK
gpg:                using RSA key 843938DF228D22F7B3742BC0D94AA3F0EFE21092
gpg: BAD signature from "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" [unknown]
```

And the files at https://cdimage.ubuntu.com/ubuntu-mate/releases/20.04/release/ look like this (note the **Last modified** date of the files):

![2021-04-07_19-53](https://user-images.githubusercontent.com/14307537/114067290-55b6c800-98a5-11eb-95cd-bf492e360928.png)

Seems SHA256SUMS file was modified later and contains wrong data.

### Link(s) to the affected pages

https://cdimage.ubuntu.com/ubuntu-mate/releases/20.04/release/

**Comment by franksmcb** [comment]
Thank you for taking the time to report this issue. 

We have opened a bug report to have the proper .gpg key posted.

https://bugs.launchpad.net/ubuntu-cdimage/+bug/1923118

**Comment by franksmcb** [comment]
The .gpg key has been updated.

Thanks again for letting us know.

 ```
 gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS
    gpg: Signature made Fri 09 Apr 2021 04:09:29 PM MDT
    gpg: using RSA key 843938DF228D22F7B3742BC0D94AA3F0EFE21092
    gpg: Good signature from "Ubuntu CD Image Automatic Signing Key (2012) cdimage@ubuntu.com"

```
