### ISSUE TITLE
Lag in software

### ISSUE THREAD

**Issue by Pandz18** [ubuntu-mate/ubuntu-mate.org#122]
Hey , 

First I would like to say , I love the software and the work y’all are doing . It’s amazing . Unfortunately I’m way under qualified to contribute in the back end  of the work . Lot’s for support to y’all guys . 

So it may be a problem with my laptop but I wasn’t sure so I just wanted to bring it to your attention . So I’m running Ubuntu Mate on Oracle VB . So when I’m using Ubuntu Mate , for the beginning time , everything works normally but then suddenly everything becomes laggy , I thought maybe it’s my system but when I used my normal system , everything is working a ok . So is it a problem with the software or the virtual machine ? 

Also a suggestion  , could y’all add a “Downloads” folder in the menu drop down ? I understand it’s on the home page in the file (username) Home but would be nice if y’all could add this . 

So yeah , again , love the work , keep up the fantastic work .

**Comment by franksmcb** [comment]
Thank you for contacting us. These look like support and/or feature requests for the project and not issues with the website.

Please go to https://ubuntu-mate.community/ and post there for these questions.
