### ISSUE TITLE
amd64 for 22.04 is not listed in «Browse Downloads»

### ISSUE THREAD

**Issue by dym-sh** [ubuntu-mate/ubuntu-mate.org#156]
amd64 for 22.04 is not listed in «Browse Downloads»

- https://releases.ubuntu-mate.org/22.04/
- https://releases.ubuntu-mate.org/jammy/

although its clearly downloadable via https://ubuntu-mate.org/download/amd64/jammy/

**Comment by flexiondotorg** [comment]
The amd64 downloads are not hosted by the Ubuntu MATE. They are hosted by the Ubuntu project here:

  - https://cdimage.ubuntu.com/ubuntu-mate/
