### ISSUE TITLE
Nvidia driver 390 doesn't work after upgrade to 23.04 (as on 22.04

### ISSUE THREAD

**Issue by Sutyke** [ubuntu-mate/ubuntu-mate.org#165]
### Details about the problem

I had trouble installing the NVIDIA 390 driver on my computer after upgrade to version 23.04. However, when I installed UBUNTU MATE 22.04, the driver worked immediately after installation, along with MATE Optimus. I appreciate the MATE Team for making this possible, as it is the only Ubuntu flavor where the NVIDIA 390 driver worked without any additional steps after installation when I upgraded in the past to 22.04.

I tried several methods to install the NVIDIA driver but was unsuccessful. Although there is possible issue with the 390 driver, I hope the MATE team can fix it since it works perfectly on UBUNTU MATE 22.04.

I followed all the suggestions from this link: https://askubuntu.com/questions/1129516/black-screen-at-boot-after-nvidia-driver-installation-on-ubuntu-18-04-2-lts but couldn’t install the NVIDIA 390 driver. So, I reinstalled UBUNTU MATE 22.04 and the driver worked right out of the box.

### Screenshots
Black screen with blinking cursor after installation Ubuntu 23.04.

### Environment
- **OS:** Ubuntu MATE 23.04

**Comment by franksmcb** [comment]
Please see this page for a how-to on bug reporting for OS issues: https://ubuntu-mate.community/t/how-to-report-problems-in-ubuntu-mate/17943
