### ISSUE TITLE
Gnome has moved to Gitlab some time ago - few apps src url needs correction

### ISSUE THREAD

**Issue by aytvill** [ubuntu-mate/ubuntu-mate.org#173]
### Details about the problem
web site urls for few default Gnome Apps point to obsolete / historical urls on Github,
for next apps: 
 - Cheese
 - Gparted
 - Orca
 - Rhythmbox 
 - Seahorse

while Gnome has moved to Gitlab

### Screenshots

(not needed)

### Link(s) to the affected pages

https://ubuntu-mate.org/get-involved/development/#default-apps

### PR for code change

I have made push request #172 , it seem to pass internal checks in CI/CD

### Environment

- **Browser:** Firefox 121.0.1/etc
- **OS:** Ubuntu MATE 20.04/

**Comment by aytvill** [comment]
@flexiondotorg any chance for these small updates?

**Comment by flexiondotorg** [comment]
Thanks for the pull request :bow: Closed via https://github.com/ubuntu-mate/ubuntu-mate.org/pull/179
