### ISSUE TITLE
Problem with download buttons and facebook container extionsion in firefox

### ISSUE THREAD

**Issue by Morgenkaff** [ubuntu-mate/ubuntu-mate.org#33]
I have no idea how these to things are connected, but when the Facebook container extension is enabled in Firefox 67, the buttons to choose architecture for the Ubuntu Mate download does not work. All other extensions are disabled.

Here is a video of the problem:
https://www.youtube.com/watch?v=ljDPi97DbZ8
At 0:12 I'm clicking the buttons.

Please let me know if there are more details I can provide.

**Comment by lah7** [comment]
Please press <kbd>F12</kbd> to open the DevTools, and paste the output of the **Console** tab when clicking the button. This should provide some details.

Seems strange as there isn't any _"Facebook code"_ (like buttons, etc) running on this site. :thinking:

**Comment by Morgenkaff** [comment]
The console doesn't output anything when the buttons are clicked. But when the page loads, with the extension enabled, it gives this error:
> Error: Permission denied to access property "__rocketLoaderInlineHandlerProxy"rocket-loader.min.js:1:9661
    proxyInlineHandler https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js:1
    updateInlineHandlers https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js:1
    finalizeActivation https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js:1
    n https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js:1
    c https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js:1

The error does not appear with the extension disabled.

**Comment by lah7** [comment]
It sounds like [Rocket Loader](https://blog.cloudflare.com/we-have-lift-off-rocket-loader-ga-is-mobile/) (a server-side optimisation enabled on our CDN, CloudFlare) is interfering. I don't actually have access to Ubuntu MATE's CloudFlare (yet) so I can't turn it off.

However, with the new website update in the upcoming month(s), the download page won't be reliant on JavaScript and that will address the issue.

**Comment by lah7** [comment]
We just launched a new website update - the download page shouldn't be a problem any more as it doesn't rely on JavaScript.
