### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by V0idk** [ubuntu-mate/ubuntu-mate.org#36]
https://ubuntu-mate.org/download/   
armv8

This is somewhat embarrassing, isn’t it?
It seems I can’t find what you’re looking for. You’ve requested a page that has moved, been removed or was never there in the first place. Try using the search above to see if you can find what you came here looking for.

**Comment by lah7** [comment]
Thanks, this was fixed.

https://ubuntu-mate.community/t/broken-download-link-for-raspberry-pi-images-18-04/19935/4?u=lah7
