### ISSUE TITLE
It took too long for me to find this GitHub repository

### ISSUE THREAD

**Issue by tsimonq2** [ubuntu-mate/ubuntu-mate.org#4]
It would be convenient if this page was linked somewhere more obvious on the website (maybe in the footer somewhere) just in case someone wants to view the code.

**Comment by epgfm** [comment]
Meh this "Recent Site Changes" lands you here. :p

**Comment by lah7** [comment]
It didn't one month ago. I forgot to reference/close this issue. 

Fixed in https://github.com/ubuntu-mate/ubuntu-mate.org/commit/ddd3d2b0cf77935a007662ac0c52912454fe61cd
