### ISSUE TITLE
Typos + text and layout suggestions/adjustments

### ISSUE THREAD

**Issue by szabiakanich** [ubuntu-mate/ubuntu-mate.org#6]
### **Page:** https://ubuntu-mate.org/

**Section:** Sponsors
**Suggestion:** center logos in the frames

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.org/what-is-ubuntu-mate/

**Section:** What is Ubuntu MATE?

**Current:**
Hopefully this page _with_ help demystify Ubuntu MATE for new-comers.

**Target:**
Hopefully this page _will_ help demystify Ubuntu MATE for new-comers.

---------------------

**Section:** Mate Desktop

**Current:**
_Wikipedia says that a Desktop Environment is:_

**Target:**
_Wikipedia defines a Desktop Environment as:_

---------------------

**Section:** Powerful Applications

**Suggestion:** The period at the end of some of the entries. Either have a period after every entry or remove all periods

---------------------

**Section:** Open Source

**Suggestion:** there should be a few more spaces after the last paragraph to bring the "Open Source" heading into a new line

---------------------

General remark/suggestion regarding the formatting: the logos for Ubuntu, Steam and Open Source should have more padding around them and the Ubuntu Logo and the Steam logo should be also moved to the right to have a cleaner layout

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.org/faq/

Will you be making a 14.04 LTS version of Ubuntu MATE?
We have, although it is not an official build. You can get it here:

Ubuntu MATE 14.04.2 LTS
We have also posted a HOW-TO for installing your own Ubuntu MATE 14.04 from scratch.

**Comment/suggestion:** this question/information is outdated, since 14.04. has been out for a while and isn't the most up to date version of Ubuntu Mate. Suggestion: remove this question from FAQ / alternatively udpate the information with a link to a 17.04. installation guide

-----------------------

Why is xyz application installed by default when I prefer abc application?
In general, the default application selection follows what shipped in Ubuntu 14.04. The only reason we deviate from the default Ubuntu applications is if they are not compatible with Ubuntu MATE or pull in lots of unnecessary dependencies.

The reason for using the default applications as shipped by Ubuntu is the Ubuntu staff support the default applications. The Ubuntu MATE team is rather small so sharing the support responsibility makes sense, both for us and our users.

**Comment/suggestion:** update the first paragraph with 17.04. or just a general info "In general, the default application selection follows what ships with the current version of Ubuntu."

------------------------

Can I use iTunes on Ubuntu MATE?
No. This is one of those programs that is specifically designed by Apple NOT to run on Linux. Although Mac OS X has its roots in the same UNIX philosphy as Linux, OS X is not the same as Linux, and applications written for Apple’s operating system do not automatically run on Linux. There are, however plenty of alternative media players that will play music, create play lists, sync with mobile devices, and retrieve, manage and play podcasts. Rythmbox is provided with Ubuntu MATE and can play any of the music or podcasts in your iTunes library.

**Comment/suggestion:**
- Mac OS X need to be replaced by macOS.
- Rythmbox missing an h

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.org/community/

**Suggestion:** Align logos with text, i.e. center the logos

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.org/download/

**Comments/suggestions:**
- add or remove periods at the end of the lines (consistency)
- Modern Intel-based Apple Macs vs. Older Intel-based Apple Macintosh systems (have both as Apple Macs or Apple Macintosh systems)
- when you click on 32bit or 64bit the tile for 17.04. reads "Interm" instead of Interim

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.org/team/ 

Adam Smith Created the initial PowerPC build of Ubuntu MATE. - _Broken link_

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.org/donate/

**Section:** Bitcoin

**Current:** Click or scan _to_ QR code below to launch
**Target:** Click or scan _the_ QR code below to launch

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** https://ubuntu-mate.boutique/

**Section:** Ubuntu MATE: Upgrading from Windows or OSX - the book

**Current:**
Also available _in Paperback on for Kindle_ from your regional Amazon store in your local currency

**Target:**
Also available _as a paperback or for Kindle_ from your regional Amazon store in your local currency:

----------------------------------------------------------------------------------------------------------------------------------------------------------

### **Page:** http://ubuntu-mate.org/logo-guidelines/

**Section:** The Circle of MATEs

**Current:** The triangles inside the roundel represent the three _foundamental_ elements of this 
**Target:** The triangles inside the roundel represent the three _fundamental_ elements of this 

--------------

**Section:** Wordmark

**Current:** 
The wordmark logo is presented only with colours above. Please, never change any of the colours in the logo. In this case, for the white logo, it has been placed a green background. It is not part of it, you are free to place the logo on whatever background you want, you just have to see it.

**Target:** 
The wordmark logo should be used only with the colours shown above. The colours should never be altered. The white logo on the right has been placed on a green background just for illustration purposes. The background is not part of the logo. You are free to place the logo on a different background, as long as the logo is clearly visible.

--------------

**Section:** Roundel

**Current:**
As for the wordmark, use the roundel logo only with the colour configurations above. For the white version, it has been added a green background only to let you see it. It is not part of it.

**Target:**
The roundel should only be used with the colours shown above. The colours should never be altered. The white logo on the right has been placed on a green background just for illustration purposes. The background is not part of the logo. You are free to place the logo on a different background, as long as the logo is clearly visible.

--------------

**Section:** Which logo should I use?

**Current:**
It has no different which logo you choose to use for your works. There isn’t a preferred version we like to see. Just select what you want so that the logo is well distinguishable. We recommend to use the white versions of the logos on darker background, and to use the coloured versions on lighter background.

**Target:**
Please make sure to use the appropriate logo for your application. There isn't a preferred version of the logo that should be used, as long as the logo is clearly visible in the context that it is being used in. We recommend using the coloured version on light backgrounds and the white logo on dark backgrounds.

--------------

**Section:** Incorrect use

**Current:**
By following the guidelines on how to use _them_ you will help to build a powerful and united identity for the Ubuntu MATE brand. This section shows examples of incorrect use.

**Target:**
By following the guidelines on how to use _the logos_ you will help build a powerful and united identity for the Ubuntu MATE brand. This section shows examples of incorrect use.

**Current:** 3. Change the colour of the Circle of _Friends_
**Target:** 3. Change the colour of the Circle of _MATEs_

--------------

**Section:** Ubuntu MATE stacked logo

**Current:** It has been made also a stacked version of the logo.
**Target:** A stacked version of the logo has also been made available.

**Comment by flexiondotorg** [comment]
@szabiakanich Please submit a pull request for these changes :smile:

**Comment by lah7** [comment]
Closing as 3 years has passed and the content has changed since.

If you see anything amiss, please use the **Improve this page** button in the footer of that page.
