### ISSUE TITLE
404 error after donating

### ISSUE THREAD

**Issue by mublinas** [ubuntu-mate/ubuntu-mate.org#65]
### Details about the problem
After donating with PayPal, 404 error Ubuntu-mate.org/funding/succes

### Screenshots
![Schermafdruk op 2020-04-12 13-14-30](https://user-images.githubusercontent.com/41875928/79067448-9a724800-7cbf-11ea-9881-a307de5bfa6f.png)

### Environment
Browser: Firefox 75.0 (64-bits)
add-ons: Privacy Badger, HTTPS Everywhere, Quick Dial, Facebook Container
OS Ubuntu Mate 18.04

**Comment by lah7** [comment]
Thanks for the report - **Yikes!** I got muddled up with the URL on my end when I was working on the new site. Sorry about that!

Thank you for contributing to the project :+1: :moneybag:

**Comment by mublinas** [comment]
Keep up the good work, thank you
