### ISSUE TITLE
Outdated Entroware specs on the webpage

### ISSUE THREAD

**Issue by shinigabi** [ubuntu-mate/ubuntu-mate.org#67]
I was checking the Ubuntu Mate shop on the Entroware ordering page (https://ubuntu-mate.org/shop/computers/), if there are laptops available with Gen10 Intel processors, but the page shows only Gen8 for the 14" Apollo.
However if I click on the link to go to Entroware's page, they only supply Gen10 Intel processors for the Apollo.
Is it possible to sync/update these pages?
![entroware_order](https://user-images.githubusercontent.com/52028937/80576118-eeda2f00-8a04-11ea-81d3-3d1862ed1ad4.PNG)
![mate_entroware](https://user-images.githubusercontent.com/52028937/80576121-ef72c580-8a04-11ea-910c-4d1176d45b58.PNG)

**Comment by madhens** [comment]
Pull request #68 addresses these issues and others. Thank you, shingabi, for reporting this!
