### ISSUE TITLE
Image in banner skewed in Safari

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate.org#74]
### Details about the problem

The banner on the home page does not use the correct aspect ratio (on large screens like Mac or iPad)

### Screenshots

From #73:

![image](https://user-images.githubusercontent.com/13032135/83763070-3725e600-a670-11ea-9f29-92b4c97bf34c.png)

### Link(s) to the affected pages

* https://ubuntu-mate.org/
* https://ubuntu-mate.org/download/amd64/bionic/thanks

### Environment

- **Browser:** Safari (Latest) and WebKitGTK
- **OS:** iOS 13

**Comment by matigo** [comment]
Possible fix in #75. Hopefully this resolves the issue I created ...
