### ISSUE TITLE
Signed SHASUMS not available for Raspberry Pi images

### ISSUE THREAD

**Issue by muxnulljack** [ubuntu-mate/ubuntu-mate.org#82]
Hello, as far as I can tell, a GPG signed hash is only offered for the amd64 images, but not the raspberry pi images. Is this something that exists, and if not, could this be added so I can verify the authenticity of the image?

**Comment by lah7** [comment]
Yes, thanks for flagging this up. :slightly_smiling_face: 

We've opened up the downloads for browsing at https://releases.ubuntu-mate.org. These contain `.sha256.sign` files which follow the same usage as Ubuntu's `SHA256SUM.gpg`.
