### ISSUE TITLE
Application is closed but window preview still appear

### ISSUE THREAD

**Issue by asharifauzan** [ubuntu-mate/ubuntu-mate.org#96]
I set window manager in `Mate Tweak` to `Marco (compton GPU Compositor)`. When i want close application i always hover pointer to its tab application then close with scroll click/three finger tap then the application is closed but the windows manager doesn't disappear unless i close application with close button in window panel. its only occur if i only open single tab and its occur 

https://ibb.co/dJ4WJ48

Ubuntu Mate 20.04

**Comment by lah7** [comment]
Sorry, but this doesn't appear to be an issue with the website (which is this repository)

Please see this page for help: https://ubuntu-mate.org/support/

**Comment by asharifauzan** [comment]
sorry i was wrong, i already create question on there. big thx
