### ISSUE TITLE
Lightning Donations

### ISSUE THREAD

**Issue by Juized** [ubuntu-mate/ubuntu-mate.org#98]
Bitcoin is going to the moon and giving donations on layer 1 don't really seem to practical anymore. Anychance you can implement a lightning integration so people can donate with the Lightning Network. It saves us money on fees and it saves you time because you dont have to wait 6 confirmations to withdraw your BTC....

**Comment by lah7** [comment]
Sorry, I flagged this to the project leader, but he isn't interested.
